### ISSUE TITLE
Launch cutover checklist

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-blog#22]
Prior to launch, tentatively scheduled for 8 April 2021.

## For @jessicaschilling 
- [x] Update top-level README.md to reflect latest info: Vuepress specifics, deploy details, maintainership, etc
- [x] Close or migrate any open issues from https://github.com/ipfs/blog/issues
- [x] Make this repo public 
- [x] Add standard org-wide issue labels and issue templates
- [ ] ~~Confirm RSS feed works as intended (close, but added additional https://github.com/ipfs/ipfs-blog/issues/119 for hotfix)~~
- [x] Protect `staging` branch so it can't be accidentally deleted upon merge?
- [x] Confirm Discourse comments display as intended (this should cut over fine as we explicitly included the preview domains in Discourse prefs, but we'll want to remove that after launch). To confirm: blog.ipfs.io, both Fleek preview domains. **NOTE** that `http://127.0.0.1:8080/ipns/blog.ipfs.io/` and `http://blog.ipfs.io.ipns.localhost:8080` are being investigated in https://github.com/ipfs/ipfs-blog/issues/80
- [x] Make sure any Hugo redirects are migrated to Vuepress redirects (https://github.com/ipfs/ipfs-blog/pull/93/ handles this)
- [x] Ensure all content published to old blog since Feb 2021 has been migrated **(NOTE: new posts are scheduled for both 7 and 8 April)**
- [x] Make sure Forestry UI link to image crop tool points to prod location
- [x] Update repo description for go-live, not staging, links
- [x] Countly: Duplicate test dashboard for prod (including 404 info)
- [x] Countly: Set up dashboard/project view permissions and weekly email to relevant folks
- [x] Update https://ipfs.io/media/ with press-kit info (@angiemaguire is reviewing https://github.com/ipfs/website/pull/421)
- [x] Training: @jennwrites, @autonome, @angiemaguire, @emilymvaughan, @achingbrain 
- [x] Forestry permissioning: Investigate with @andyschwab whether this can be driven entirely from GitHub auth and groups; add users/roles as needed
- [x] Sync staging and main one last time
- [x] Send internal email and create meeting slide
- [x] Write blog post

## For @jdiogopeixoto and/or @zebateira 
- [x] Confirm we won't accidentally spam Discourse when we cut over (or remediate)
- [x] Remove ability to write directly to `main` from Forestry
- [x] Change Fleek CANONICAL_BASE env variable (in both prod and staging) from https://ipfs-blog.on.fleek.co to to https://blog.ipfs.io
- [x] Get Countly working in prod environment
- [x] 404 page: [not working at the moment](https://ipfs-blog.on.fleek.co/asdf) – fleek uses ipfs under the hood, so the 404s only works if we setup it up ipfs-friendly (example: https://github.com/ProtoSchool/protoschool.github.io/pull/550/files)
    - [x] add file `ipfs-404.html` to the root of the build folder
    - [x] add route `/404` instead of rendering it in the unknown route

## For others
- [x] Confirm no URIs will break **(If everyone can lend a hand with this, would be ideal!)**
- [x] DNS switching (@andyschwab):
    - [x] Stage a PR in infra repo for cutting over DNS
    - [x] Merge and confirm after approx 10min
- [x] Move https://github.com/ipfs/blog into `ipfs-inactive` org (@jessicaschilling will file a support ticket for this; it's not time-critical but let's at least get ticket in at launch time)
