### ISSUE TITLE
Basic branding/visual review

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-blog#43]
## To do
Consolidated checklist in this comment summarizes the discussion in the comments underneath ...

**Note that this doesn't include font consistency issues ... will take a closer look at those in https://github.com/ipfs/ipfs-blog/issues/36.**

- [x] To increase readability of long lines of text, please modify H2 on pages without header images to max out at something similar to this:
![image](https://user-images.githubusercontent.com/1507828/108565994-e9ffa800-72c2-11eb-8e0b-9e2a634cc812.png)
- [x] To increase readability of long lines of text, please modify body width on individual post pages to something closer to that on the [Filecoin blog](https://protocol.ai/blog/pl-participation-in-the-filecoin-economy/). This probably means modifying the header width on individual post pages so it doesn't look significantly wider than the body — suggestions welcome on this, but something along this might work (note enlarging hero image to make it feel a little more balanced):
![image](https://user-images.githubusercontent.com/1507828/108566874-5d55e980-72c4-11eb-926e-37f4d14a2ce0.png)

- [x] On individual post pages at mobile widths, please add a bit more horizontal margin to the post body area - this looks a little too tight:
![image](https://user-images.githubusercontent.com/1507828/109052533-f0ae6680-7698-11eb-96d0-51d59edff0fd.png)

- [x] Also on individual post pages at mobile widths, please tidy up the chicklets and share links so they don't share a div or word-wrap within chicklets: 
![image](https://user-images.githubusercontent.com/1507828/109060724-fa3ccc00-76a2-11eb-9051-9435ed323657.png)

- [x] Please remove the breadcrumb from the cards page; on individual post pages, add a small subheader for "Blog & news" as in the following:
![image](https://user-images.githubusercontent.com/1507828/108571893-57fd9c80-72ce-11eb-97cc-1c0994e282d4.png)

- [x] When links are on a dark blue background, please use #6bc4ce instead of the existing link color.

- [x] Please make visual modifications to the language picker as described in https://github.com/ipfs/ipfs-blog/issues/47.
- [x] On all pages, please change page background to #f1f3f2; on card pages, make cards all white for better card visibility (no need for shadow now). Please don't rip out any of the logic behind identifying blog posts, though; I still suspect we will still need to differentiate these somehow, but let's see what happens in user testing.
- [x] On cards page, now that background is in color, please remove outlines from form fields: 
![image](https://user-images.githubusercontent.com/1507828/108765178-b87c1c00-7510-11eb-9aac-d8ea86cf6292.png)

- [x] On cards page, please change highlight color to #9ad4db instead of current pink
- [x] In search filter, please add single quotes around "enter" in `Press 'enter' to select`
- [x] On cards, please rearrange content elements as such: 
![image](https://user-images.githubusercontent.com/1507828/108765781-769fa580-7511-11eb-8dde-d4a760db4e43.png)

- [x] Also based on the mockup immediately above, please make all chicklets gray and highlight them with [ipfs-css](https://github.com/ipfs-shipyard/ipfs-css) `charcoal-muted` on hover.
- [x] However, please apply this visual treatment for blog post chicklets to make them "special" (sorry this is in a different mockup!) 
![image](https://user-images.githubusercontent.com/1507828/108767668-edd63900-7513-11eb-8546-c8e6bf514d70.png)

- [x] On cards, please display full card title when hovering on card title (as alt text) so that titles truncated with ellipses can be read in full

- [x] The `blueGreen` color value used in text links and button backgrounds should be #34797D (understood that isn't in the main ipfs-css set, but `teal` is not quite WCAG-compliant on the new background noted above).
- [x] On individual blog post pages, please add the same corner radius to the hero image as there is on the cards themselves.
- [x] On individual blog post pages, please de-emphasize tag chicklets by using a lighter background (ipfs-css `gray-muted` might work out of the box): 
![image](https://user-images.githubusercontent.com/1507828/108769456-3ee72c80-7516-11eb-8f57-959620ace6d3.png)

- [x] Please add visual formatting for code blocks as described in https://github.com/ipfs/ipfs-blog/issues/33 - inline code display is already OK, but still need to match visual formatting for multi-line blocks of code.
